### ISSUE TITLE
Extending to CVC4?

### ISSUE THREAD

**Issue by dtwelch** [tudo-aqua/z3-turnkey#1]
This is a neat library! Here's a question: How difficult do you think it would be to do something like this with CVC4? I realize this is the z3-turnkey repo, but seemed like a reasonable place to ask. Honestly there could even be a separate repo for that. 

I was hoping to use CVC4's java bindings in my tool while at the same time keeping end-users lives as simple as possible (The reason I wanted cvc is mainly because it has native support for higher-order functions, activated by the --uf-ho flag).

I'll see how far I can get with it myself, but figured you'd be the one to ask :-)

**Comment by no-preserve-root** [comment]
Thanks!

As for CVC4: the unpack-and-link at runtime would certainly work. However, the CVC4 authors do not publish prebuilt libraries, so these would have to be built for all target OS's. In theory, this might be possible using cross-compilation, but it would not be as easy as packaging Z3.

**Comment by no-preserve-root** [comment]
I've created [prebuilt libraries](https://github.com/tudo-aqua/cvc4-azure-build) for Linux and OSX. Compiling all dependencies on Windows seems to be extremely difficult and a reduced version of the solver would mean different per-OS behaviors.

The [TurnKey version](https://github.com/tudo-aqua/cvc4-turnkey) (Java + unpacking libraries) is also available as both a GPL and non-GPL build.
