### ISSUE TITLE
Update to Z3 4.9 series

### ISSUE THREAD

**Issue by no-preserve-root** [tudo-aqua/z3-turnkey#14]
See https://github.com/Z3Prover/z3/releases/tag/z3-4.9.0 and https://github.com/Z3Prover/z3/releases/tag/z3-4.9.1

**Comment by thpani** [comment]
Hi and thanks again for maintaining this useful utility :)

With Z3 4.11 out, we could use access to an updated version; would it be possible to cut a release? Anything I can do to help?

**Comment by mmuesly** [comment]
The original releases for Z3 4.9.0 and 4.9.1 contain a libz3java.dylib build for amd64. Therefore, we skipped them. I released the newer versions starting with 4.10.0 and confirmed that they are correctly loaded on a M1 OSX machine. CI loads them as well so I expect them to work.
