### ISSUE TITLE
memory leak issue

### ISSUE THREAD

**Issue by syheliel** [tudo-aqua/z3-turnkey#17]
First, thanks for your project! I use your z3 repo in my project. But I find that when it handles a large amount of queries, the allocated memory is increasing and finally leads to a system "kill".

Here is the pmap: The area in the red square seems to be related to libz3.so and it takes lots of bytes.
![58ffa5f6-986b-4d37-bfe2-11248cb0cd35](https://github.com/tudo-aqua/z3-turnkey/assets/45957390/716d6963-4788-4028-a3cf-82eea1cadc1f)

I'd like to provide additional info if necessary.

**Comment by syheliel** [comment]
Here is my repo that uses z3-turnkey: https://github.com/syheliel/jconstraints-z3

**Comment by fhowar** [comment]
It seems that you base off a very old version of jconstraints-z3, which is not maintained anymore. We integrated jaconstraints-z3 into jconstraints.

Please check If you could use https://github.com/tudo-aqua/jconstraints/

**Comment by syheliel** [comment]
> It seems that you base off a very old version of jconstraints-z3, which is not maintained anymore. We integrated jaconstraints-z3 into jconstraints.
> 
> Please check If you could use https://github.com/tudo-aqua/jconstraints/

Thanks, I will try it later
