### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No native libraries present for LINUX on AARCH64

### ISSUE THREAD

**Issue by AlienKevin** [tudo-aqua/z3-turnkey#18]
Hi, I'm using z3-turnkey in a Debian docker container that runs on a M1 mac. Is there a way to build z3-turnkey for AARCH64 Linux? Thanks

**Comment by no-preserve-root** [comment]
At the moment, we are only packaging the binaries provided by Z3. If they are interested in releasing an official build for aarch64, we could simply package that, otherwise, we could theoretically build the libraries for linux/aarch64 ourselves. Could you open an issue at the Z3 project?

**Comment by AlienKevin** [comment]
I see, makes sense. I will open an issue at Z3.

**Comment by no-preserve-root** [comment]
Currently blocked by https://github.com/Z3Prover/z3/issues/7201

**Comment by wxie7** [comment]
According to this comment https://github.com/Z3Prover/z3/issues/7201#issuecomment-2387192712, the ARM64 issue should be fixed. Could you please add support for ARM64?

**Comment by no-preserve-root** [comment]
The current 4.12.2 and 4.13.3 builds are broken on Windows: https://github.com/Z3Prover/z3/issues/7420. As soon as that is fixed (hopefully in 4.13.4), I'll build a version with ARM64 support.

**Comment by no-preserve-root** [comment]
4.13.4 with Linux/aarch64 support and fixes Windows builds is released (should be available in a few hours ar most)
