### ISSUE TITLE
UnsatisfiedLink /tmp/z3-turnkeyXXXXXX/libz3.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by salimane** [tudo-aqua/z3-turnkey#19]
Hi, I'm using z3-turnkey in a Debian docker container `bellsoft/liberica-openjdk-debian:21`  and I am getting the error

```
UnsatisfiedLink /tmp/z3-turnkey707272457078847883/libz3.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/z3-turnkey707272457078847883/libz3.so)
```

is there a way to resolve this ? @thpani @no-preserve-root

Thanks

**Comment by intrigus-lgtm** [comment]
I believe this is an effect of https://github.com/tudo-aqua/z3-turnkey/commit/ea76bd5498d477da9ce9965ac093c5d2c97d9e18
This commit switches from glibc-2.31 to glibc-2.35.
So your container needs to have at least glibc-2.35.
I believe _latest_ debian should have a sufficient version.

**Comment by salimane** [comment]
Oh, I see, I will downgrade the `z3-turnkey` version to `4.8.17`. Thanks for the pointer

**Comment by intrigus-lgtm** [comment]
@salimane 4.11.2 would probably also work.

**Comment by no-preserve-root** [comment]
Z3 4.12.2 also ships a version linked against glibc 2.31 (4.12.0 and 4.12.1 didn't). I'll update the build to use that distribution for the linux binaries and release a version 4.12.2.1.
